// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(UpdateListContext))]
    [Migration("20220126212324_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.UpdateList", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            Title = "The Secret Life of Walter Mitty",
                            Category = "Family",
                            Director = "Ben Stiller",
                            Edited = false,
                            LentTo = "No one",
                            Notes = "Best movie ever made",
                            Rating = "PG",
                            Year = 2013
                        },
                        new
                        {
                            Title = "The Lego Movie",
                            Category = "Family",
                            Director = "Phil Lord, Chris Miller",
                            Edited = false,
                            LentTo = "No one",
                            Notes = "Another wonderful film",
                            Rating = "PG",
                            Year = 2014
                        },
                        new
                        {
                            Title = "Captain America: Civil War",
                            Category = "Action/Adventure",
                            Director = "Joe Russo, Anthony Russo",
                            Edited = false,
                            LentTo = "Bucky",
                            Notes = "Best Cap'n America movie",
                            Rating = "PG-13",
                            Year = 2016
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
